default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  encoding: utf8
  database: shiny_dev
  host: localhost
  pool: 5
  username: shiny
  password: shiny_secret 

production:
  <<: *default
  database: largobox_arasa49
  encoding: utf8
  username: largobox_arasa49
  password: naB1uFGbVfh
  host: postgresql0.locum.ru
  port: 5432